apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-output
  namespace: image-builder
  labels:
    app.kubernetes.io/part-of: omnia-image-builder
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-builder-workspace
  namespace: image-builder
  labels:
    app.kubernetes.io/part-of: omnia-image-builder
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
